CREATE TABLE TB_INFO(
    INFO_NO NUMBER(2) PRIMARY KEY NOT NULL
    ,PC_NO VARCHAR2(10) UNIQUE NOT NULL
    ,NM VARCHAR2(20) NOT NULL
    ,EMAIL VARCHAR2(50) NOT NULL
    ,HOBBY VARCHAR2(1000)
    ,TEAM NUMBER(2)
    ,CREATE_DT DATE DEFAULT SYSDATE
    ,UPDATE_DT DATE DEFAULT SYSDATE
);
SELECT * FROM tb_info;

SELECT info_no,pc_no,nm,email FROM tb_info 
ORDER BY PC_NO;