SELECT MEM_NAME , MEM_JOB , MEM_LIKE ,MEM_MILEAGE,
    CASE WHEN MEM_MILEAGE <5000 THEN 'SILVER'
    WHEN MEM_MILEAGE >=5000 AND MEM_MILEAGE <8000 THEN 'GOLD'
    ELSE  'VIP'
    END AS GRADE
FROM MEMBER
WHERE MEM_JOB = '주부' OR 
MEM_JOB ='회사원' OR 
MEM_JOB ='자영업'
ORDER BY MEM_MILEAGE desc;
--- 출력에는 없지만 테이블 안에 존재하는 컬럼으로 정렬이 가능하다.